# Generated by Django 5.0.1 on 2025-10-08 09:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "supabase_user_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "telephone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("nom_complet", models.CharField(max_length=255)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("langue", models.CharField(default="fr", max_length=5)),
                (
                    "fuseau_horaire",
                    models.CharField(default="Africa/Abidjan", max_length=50),
                ),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("actif", models.BooleanField(default=True)),
                ("email_verifie", models.BooleanField(default=False)),
                ("telephone_verifie", models.BooleanField(default=False)),
                (
                    "date_verification_email",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "date_verification_telephone",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("derniere_connexion", models.DateTimeField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("date_suppression", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "utilisateurs",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="CodeOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("email", "Email"), ("telephone", "Téléphone")],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("code", models.CharField(max_length=6)),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("inscription", "Inscription"),
                            ("connexion", "Connexion"),
                            ("verification", "Vérification"),
                            ("reset_password", "Réinitialisation mot de passe"),
                        ],
                        max_length=50,
                    ),
                ),
                ("utilise", models.BooleanField(default=False)),
                ("date_utilisation", models.DateTimeField(blank=True, null=True)),
                ("tentatives", models.IntegerField(default=0)),
                ("max_tentatives", models.IntegerField(default=3)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_expiration", models.DateTimeField()),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes_otp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code OTP",
                "verbose_name_plural": "Codes OTP",
                "db_table": "codes_otp",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["code", "type"], name="codes_otp_code_d1d70a_idx"
                    ),
                    models.Index(fields=["email"], name="codes_otp_email_4b5044_idx"),
                    models.Index(
                        fields=["telephone"], name="codes_otp_telepho_a1b001_idx"
                    ),
                    models.Index(
                        fields=["-date_creation"], name="codes_otp_date_cr_6229ec_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionUtilisateur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_expiration", models.DateTimeField()),
                (
                    "derniere_activite",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_deconnexion", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session utilisateur",
                "verbose_name_plural": "Sessions utilisateur",
                "db_table": "sessions_utilisateur",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "active"],
                        name="sessions_ut_utilisa_61d710_idx",
                    ),
                    models.Index(fields=["token"], name="sessions_ut_token_5629dd_idx"),
                    models.Index(
                        fields=["-date_creation"], name="sessions_ut_date_cr_9c358a_idx"
                    ),
                ],
            },
        ),
    ]
