# Generated by Django 5.0.1 on 2025-10-08 14:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("icone", models.CharField(max_length=50)),
                ("couleur", models.CharField(max_length=20)),
                ("ordre", models.IntegerField(default=0)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catégorie d'intégration",
                "verbose_name_plural": "Catégories d'intégration",
                "db_table": "categories_integration",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.RemoveField(
            model_name="utilisateur",
            name="derniere_connexion",
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="last_login",
            field=models.DateTimeField(
                blank=True, db_column="derniere_connexion", null=True
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("description_courte", models.CharField(max_length=200)),
                ("icone", models.CharField(max_length=50)),
                ("couleur", models.CharField(max_length=20)),
                ("image", models.URLField(blank=True, null=True)),
                ("types_entreprise", models.JSONField(default=list)),
                ("actif_par_defaut", models.BooleanField(default=False)),
                ("gratuit", models.BooleanField(default=True)),
                (
                    "prix_mensuel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fonctionnalites", models.JSONField(default=list)),
                ("necessite_configuration", models.BooleanField(default=False)),
                ("documentation_url", models.URLField(blank=True)),
                ("video_demo_url", models.URLField(blank=True)),
                ("ordre", models.IntegerField(default=0)),
                ("populaire", models.BooleanField(default=False)),
                ("nouveau", models.BooleanField(default=False)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="accounts.categorieintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intégration",
                "verbose_name_plural": "Intégrations",
                "db_table": "integrations",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationUtilisateur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("configuration", models.JSONField(default=dict)),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("api_secret", models.CharField(blank=True, max_length=500)),
                ("webhook_url", models.URLField(blank=True)),
                ("nombre_utilisations", models.IntegerField(default=0)),
                ("derniere_utilisation", models.DateTimeField(blank=True, null=True)),
                (
                    "date_activation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_desactivation", models.DateTimeField(blank=True, null=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.integration",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intégration utilisateur",
                "verbose_name_plural": "Intégrations utilisateur",
                "db_table": "integrations_utilisateur",
                "unique_together": {("utilisateur", "integration")},
            },
        ),
    ]
